export const SUBJECT_PROGRESS = "/dev/v1/subject-progress?userId="
export const SUBJECT_HEAT_MAP = "/dev/v1/knowledge-heatmap?userId="
export const TOOL_USAGE = "/dev/v1/learning-tool?userId="
export const STUDY_PERFORMANCE_ANALYTICS = "/dev/v1/study-performance?userId="
export const MASTERY_DISTRIBUTION = "/dev/v1/mastery-distribution?userId="
export const WEEKLY_REVIEW_PATTERN = "/dev/v1/weekly-pattern?userId="
export const BODY_SYSTEM_COMPLETION = "/dev/v1/body-system?userId="
export const RETENTION_ANALYTICS = "/dev/v1/retention-analysis?userId="
export const TIME_SPENT_PER_SUBJECT = "/dev/v1/time-spent?userId="
export const CONFIDENCE_ACCURACY = "/dev/v1/attempt-confidence?userId="
export const WEAK_TOPICS = "/dev/v1/weak-topics?userId="
export const FLASHCARD_ANALYTICS = "/dev/v1/flashcard-analytics?userId="
export const EXAM_PERFORMANCE_ANALYTICS = "/dev/v1/exam-performance?userId="
export const WORK_BREAK_RATIO = "/dev/v1/work-break?userId="
export const ANSWER_CHANGE_PATTERNS = "/dev/v1/answer-pattern?userId="

export const TOPIC_PERFORMANCE = "/dev/v1/topic-performance?userId="